"""Generated action metadata; do not edit directly."""

ACTIONS = {
    'meal': frozenset(('commit_record', 'delete', 'nutrition_estimate', 'preview_record', 'query', 'record', 'record_cooking', 'record_prepared', 'save_recipe', 'suggest_recipes', 'preview_meal_plan', 'update',)),
    'water': frozenset(('delete', 'query', 'record', 'update',)),
    'weight': frozenset(('delete', 'query', 'record', 'update',)),
    'pantry': frozenset(('cancel_shopping_list', 'commit_shopping_list', 'add', 'adjust', 'commit_add', 'commit_deduct', 'commit_link_nutrition', 'commit_update_metadata', 'discard', 'deduct', 'freeze', 'open', 'preview_add', 'preview_deduct', 'preview_link_nutrition', 'preview_shopping_list', 'preview_update_metadata', 'query', 'query_shopping_list', 'search', 'thaw',)),
    'transaction': frozenset(('get_recent', 'redo', 'undo',)),
    'report': frozenset(('cost_summary', 'daily', 'expiring_inventory', 'insights', 'monthly', 'progress', 'today', 'trend_summary', 'waste_summary', 'weekly',)),
    'system': frozenset(('backup', 'commit_delete_data', 'commit_nutrition_backfill', 'export_data', 'forget_preference', 'import_data', 'initialize', 'maintenance_history', 'maintenance_status', 'migrate', 'preview_delete_data', 'query_goals', 'query_nutrition_backfill', 'query_preferences', 'repair', 'restore', 'self_check', 'update_goals', 'update_preferences', 'validate_import', 'validate_database',)),
}

DEFAULT_ACTIONS = {
    'meal': ('record', 'preview_record', 'commit_record', 'query', 'update', 'delete', 'record_cooking', 'record_prepared'),
    'water': ('record', 'query', 'update', 'delete'),
    'weight': ('record', 'query', 'update', 'delete'),
    'pantry': ('add', 'preview_add', 'commit_add', 'query', 'search', 'adjust', 'deduct', 'discard', 'open', 'freeze', 'thaw', 'preview_update_metadata', 'commit_update_metadata', 'preview_link_nutrition', 'commit_link_nutrition'),
    'transaction': ('get_recent', 'undo', 'redo'),
    'report': ('progress', 'expiring_inventory', 'insights'),
    'system': ('query_goals', 'update_goals', 'query_preferences', 'update_preferences', 'forget_preference'),
}

ACTION_HANDLER_NAMES = {
    'meal': {'commit_record': '_meal_commit', 'delete': '_meal_delete', 'nutrition_estimate': '_meal_nutrition_estimate', 'preview_record': '_meal_preview', 'query': '_meal_query', 'record': '_meal_record', 'record_cooking': '_meal_record_cooking', 'record_prepared': '_meal_record_prepared', 'save_recipe': '_meal_save_recipe', 'suggest_recipes': '_meal_suggest_recipes', 'preview_meal_plan': '_meal_preview_meal_plan', 'update': '_meal_update'},
    'water': {'delete': '_water_delete', 'query': '_water_query', 'record': '_water_record', 'update': '_water_update'},
    'weight': {'delete': '_weight_delete', 'query': '_weight_query', 'record': '_weight_record', 'update': '_weight_update'},
    'pantry': {'cancel_shopping_list': '_pantry_cancel_shopping_list', 'commit_shopping_list': '_pantry_commit_shopping_list', 'add': '_pantry_add', 'adjust': '_pantry_adjust', 'commit_add': '_pantry_commit_add', 'commit_deduct': '_pantry_commit_deduct', 'commit_link_nutrition': '_pantry_commit_link_nutrition', 'commit_update_metadata': '_pantry_commit_update_metadata', 'discard': '_pantry_discard', 'deduct': '_pantry_deduct', 'freeze': '_pantry_freeze', 'open': '_pantry_open', 'preview_add': '_pantry_preview_add', 'preview_deduct': '_pantry_preview_deduct', 'preview_link_nutrition': '_pantry_preview_link_nutrition', 'preview_shopping_list': '_pantry_preview_shopping_list', 'preview_update_metadata': '_pantry_preview_update_metadata', 'query': '_pantry_query', 'query_shopping_list': '_pantry_query_shopping_list', 'search': '_pantry_search', 'thaw': '_pantry_thaw'},
    'transaction': {'get_recent': '_transaction_recent', 'redo': '_transaction_redo', 'undo': '_transaction_undo'},
    'report': {'cost_summary': '_report_cost_summary', 'daily': '_report_daily', 'expiring_inventory': '_report_expiring', 'insights': '_report_insights', 'monthly': '_report_monthly', 'progress': '_report_progress', 'today': '_report_today', 'trend_summary': '_report_trend_summary', 'waste_summary': '_report_waste_summary', 'weekly': '_report_weekly'},
    'system': {'backup': '_system_backup', 'commit_delete_data': '_system_commit_delete_data', 'commit_nutrition_backfill': '_system_commit_nutrition_backfill', 'export_data': '_system_export_data', 'forget_preference': '_system_forget_preference', 'import_data': '_system_import_data', 'initialize': '_system_initialize', 'maintenance_history': '_system_maintenance_history', 'maintenance_status': '_system_maintenance_status', 'migrate': '_system_migrate', 'preview_delete_data': '_system_preview_delete_data', 'query_goals': '_system_query_goals', 'query_nutrition_backfill': '_system_query_nutrition_backfill', 'query_preferences': '_system_query_preferences', 'repair': '_system_repair', 'restore': '_system_restore', 'self_check': '_system_self_check', 'update_goals': '_system_update_goals', 'update_preferences': '_system_update_preferences', 'validate_import': '_system_validate_import', 'validate_database': '_system_validate_database'},
}

ACTION_POLICIES = {
    ('meal', 'commit_record'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('meal', 'delete'): ('mutation', 'none', 'operation_receipt'),
    ('meal', 'nutrition_estimate'): ('read', 'none', 'safe_read'),
    ('meal', 'preview_record'): ('read', 'conditional', 'safe_read'),
    ('meal', 'query'): ('read', 'none', 'safe_read'),
    ('meal', 'record'): ('mutation', 'conditional', 'operation_receipt'),
    ('meal', 'record_cooking'): ('mutation', 'conditional', 'operation_receipt'),
    ('meal', 'record_prepared'): ('mutation', 'none', 'operation_receipt'),
    ('meal', 'save_recipe'): ('mutation', 'none', 'operation_receipt'),
    ('meal', 'suggest_recipes'): ('read', 'none', 'safe_read'),
    ('meal', 'preview_meal_plan'): ('read', 'none', 'safe_read'),
    ('meal', 'update'): ('mutation', 'none', 'operation_receipt'),
    ('water', 'delete'): ('mutation', 'none', 'operation_receipt'),
    ('water', 'query'): ('read', 'none', 'safe_read'),
    ('water', 'record'): ('mutation', 'none', 'operation_receipt'),
    ('water', 'update'): ('mutation', 'none', 'operation_receipt'),
    ('weight', 'delete'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('weight', 'query'): ('read', 'none', 'safe_read'),
    ('weight', 'record'): ('mutation', 'none', 'operation_receipt'),
    ('weight', 'update'): ('mutation', 'none', 'operation_receipt'),
    ('pantry', 'cancel_shopping_list'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('pantry', 'commit_shopping_list'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('pantry', 'add'): ('mutation', 'conditional', 'operation_receipt'),
    ('pantry', 'adjust'): ('mutation', 'none', 'operation_receipt'),
    ('pantry', 'commit_add'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('pantry', 'commit_deduct'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('pantry', 'commit_link_nutrition'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('pantry', 'commit_update_metadata'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('pantry', 'discard'): ('mutation', 'none', 'operation_receipt'),
    ('pantry', 'deduct'): ('mutation', 'none', 'operation_receipt'),
    ('pantry', 'freeze'): ('mutation', 'none', 'operation_receipt'),
    ('pantry', 'open'): ('mutation', 'none', 'operation_receipt'),
    ('pantry', 'preview_add'): ('read', 'conditional', 'safe_read'),
    ('pantry', 'preview_deduct'): ('read', 'none', 'safe_read'),
    ('pantry', 'preview_link_nutrition'): ('read', 'none', 'safe_read'),
    ('pantry', 'preview_shopping_list'): ('read', 'none', 'safe_read'),
    ('pantry', 'preview_update_metadata'): ('read', 'none', 'safe_read'),
    ('pantry', 'query'): ('read', 'none', 'safe_read'),
    ('pantry', 'query_shopping_list'): ('read', 'none', 'safe_read'),
    ('pantry', 'search'): ('read', 'none', 'safe_read'),
    ('pantry', 'thaw'): ('mutation', 'none', 'operation_receipt'),
    ('transaction', 'get_recent'): ('read', 'none', 'safe_read'),
    ('transaction', 'redo'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('transaction', 'undo'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('report', 'cost_summary'): ('read', 'none', 'safe_read'),
    ('report', 'daily'): ('derived_file', 'none', 'safe_read'),
    ('report', 'expiring_inventory'): ('read', 'none', 'safe_read'),
    ('report', 'insights'): ('read', 'none', 'safe_read'),
    ('report', 'monthly'): ('derived_file', 'none', 'safe_read'),
    ('report', 'progress'): ('read', 'none', 'safe_read'),
    ('report', 'today'): ('derived_file', 'none', 'safe_read'),
    ('report', 'trend_summary'): ('read', 'none', 'safe_read'),
    ('report', 'waste_summary'): ('read', 'none', 'safe_read'),
    ('report', 'weekly'): ('derived_file', 'none', 'safe_read'),
    ('system', 'backup'): ('maintenance', 'none', 'no_blind_retry'),
    ('system', 'commit_delete_data'): ('maintenance', 'required_true', 'no_blind_retry'),
    ('system', 'commit_nutrition_backfill'): ('mutation', 'workflow_handle', 'operation_receipt'),
    ('system', 'export_data'): ('maintenance', 'none', 'no_blind_retry'),
    ('system', 'forget_preference'): ('mutation', 'none', 'operation_receipt'),
    ('system', 'import_data'): ('maintenance', 'required_true', 'no_blind_retry'),
    ('system', 'initialize'): ('maintenance', 'none', 'no_blind_retry'),
    ('system', 'maintenance_history'): ('read', 'none', 'safe_read'),
    ('system', 'maintenance_status'): ('read', 'none', 'safe_read'),
    ('system', 'migrate'): ('maintenance', 'none', 'no_blind_retry'),
    ('system', 'preview_delete_data'): ('read', 'workflow_handle', 'safe_read'),
    ('system', 'query_goals'): ('read', 'none', 'safe_read'),
    ('system', 'query_nutrition_backfill'): ('read', 'none', 'safe_read'),
    ('system', 'query_preferences'): ('read', 'none', 'safe_read'),
    ('system', 'repair'): ('maintenance', 'none', 'no_blind_retry'),
    ('system', 'restore'): ('maintenance', 'required_true', 'no_blind_retry'),
    ('system', 'self_check'): ('read', 'none', 'safe_read'),
    ('system', 'update_goals'): ('mutation', 'none', 'operation_receipt'),
    ('system', 'update_preferences'): ('mutation', 'none', 'operation_receipt'),
    ('system', 'validate_import'): ('read', 'workflow_handle', 'safe_read'),
    ('system', 'validate_database'): ('read', 'none', 'safe_read'),
}

FORMAL_MUTATION_ACTIONS = frozenset(
    {
        ('meal', 'commit_record'),
        ('meal', 'delete'),
        ('meal', 'record'),
        ('meal', 'record_cooking'),
        ('meal', 'record_prepared'),
        ('meal', 'save_recipe'),
        ('meal', 'update'),
        ('water', 'delete'),
        ('water', 'record'),
        ('water', 'update'),
        ('weight', 'delete'),
        ('weight', 'record'),
        ('weight', 'update'),
        ('pantry', 'cancel_shopping_list'),
        ('pantry', 'commit_shopping_list'),
        ('pantry', 'add'),
        ('pantry', 'adjust'),
        ('pantry', 'commit_add'),
        ('pantry', 'commit_deduct'),
        ('pantry', 'commit_link_nutrition'),
        ('pantry', 'commit_update_metadata'),
        ('pantry', 'discard'),
        ('pantry', 'deduct'),
        ('pantry', 'freeze'),
        ('pantry', 'open'),
        ('pantry', 'thaw'),
        ('transaction', 'redo'),
        ('transaction', 'undo'),
        ('system', 'commit_nutrition_backfill'),
        ('system', 'forget_preference'),
        ('system', 'update_goals'),
        ('system', 'update_preferences'),
    }
)

SKILL_ROUTES = {
    'meal_record': ('meal', 'record'),
    'prepared_meal_record': ('meal', 'record_prepared'),
    'cooking_record': ('meal', 'record_cooking'),
    'water_record': ('water', 'record'),
    'weight_record': ('weight', 'record'),
    'pantry_search': ('pantry', 'search'),
    'pantry_add': ('pantry', 'add'),
    'pantry_deduct': ('pantry', 'deduct'),
    'pantry_discard': ('pantry', 'discard'),
    'recent_operations': ('transaction', 'get_recent'),
    'undo': ('transaction', 'undo'),
    'redo': ('transaction', 'redo'),
    'daily_progress': ('report', 'progress'),
    'self_check': ('system', 'self_check'),
}
